### ISSUE TITLE
Full_Results.csv is missing

### ISSUE THREAD

**Issue by JannisBush** [awareseven/Reproducibility-and-Replicability-of-Web-Measurement-Studies#2]
Hi,
Thanks for open-sourcing this cool project.
I am currently having a look through the available data and it seems like `Full_Results.csv` which is used in the paper analysis script is missing.
https://github.com/awareseven/Reproducibility-and-Replicability-of-Web-Measurement-Studies/blob/38953c70a9ab03e1d29e4f9c6da13ffcaaeac84b/04_Paper_Survey/analyze_papers.R#L22

Best regards,
Jannis

**Comment by nrllh** [comment]
Hi, Jannis, sorry I missed your issue.

After discussing with the reviewers, we've decided not to publish the raw results for each paper. We have included a report for that in the paper:

> Self-Reflection This work focuses on reproducibility and repli-
> cability of Web measurement studies and highlights the need for
> proper documentation and provision of needed supplementary ma-
> terial. However, in line with similar works [8, 52, 57], we chose not
> to publish the raw results of the categorization process. It is not
> our intention to blame individual works for flaws—for which our
> own papers are no exception—but to raise awareness for a general
> potential problem in our community.
